package org.accounting.system.mappers;

import org.mapstruct.Mapper;
import org.bson.types.ObjectId;

/**
 * This utility class transforms the generated by the mongo database {@link ObjectId unique identifiers} to String and vice versa.
 * Various {@link Mapper Mappers} make use of this class.
 */
public class UtilMapper {

    /**
     * This method turns an {@link ObjectId ObjectId} into {@link String String}.
     * @param objectId The generated unique identifier by the mongo database.
     * @return The given unique identifier to String.
     */
    public String asString(ObjectId objectId) {
        return objectId.toString();
    }

    /**
     * This method turns a {@link String String} into {@link ObjectId ObjectId}.
     * @param objectId The generated unique identifier by the mongo database as a String.
     * @return The given String to ObjectId.
     */
    public ObjectId asObjectId(String objectId) {
        return new ObjectId(objectId);
    }
}
